services:
  cassandra:
    container_name: ddb-task5-cassandra
    image: cassandra:5.0
    ports:
      - "${CASSANDRA_PORT:-9042}:9042"
    environment:
      - CASSANDRA_USER=${CASSANDRA_USERNAME}
      - CASSANDRA_PASSWORD=${CASSANDRA_PASSWORD}
    volumes:
      - cassandra_data:/var/lib/cassandra
      - ./cassandra-config/cassandra.yaml:/etc/cassandra/cassandra.yaml
    healthcheck:
      test: ["CMD-SHELL", "cqlsh -u ${CASSANDRA_USERNAME} -p ${CASSANDRA_PASSWORD} -e 'SHOW VERSION'"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    container_name: ddb-task5-app
    build: .
    depends_on:
      cassandra:
        condition: service_healthy
    environment:
      - CASSANDRA_HOST=cassandra
      - CASSANDRA_PORT=${CASSANDRA_PORT:-9042}
      - CASSANDRA_USERNAME=${CASSANDRA_USERNAME}
      - CASSANDRA_PASSWORD=${CASSANDRA_PASSWORD}
      - CASSANDRA_KEYSPACE=${CASSANDRA_KEYSPACE:-online_store}
    volumes:
      - ./app:/app

volumes:
  cassandra_data: 